name: Deploy

on:
  push:
    branches:
      - main

jobs:
  front-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "capstone-group15"
          heroku_email: "rcernatescu@myseneca.ca"
  back-end:
    runs-on: ubuntu-latest
    steps:
      - working-directory: backend
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "capstone-group15-endpoint"
          heroku_email: "rcernatescu@myseneca.ca"
